require.config({
    baseUrl: appUrl,
    waitSeconds: 0,
    urlArgs: "apv=" + app_version,
    // alias libraries paths.  Must set 'angular'
    paths: {
        'jquery': 'vendor/jquery/jquery-1.11.1.min',
        'jquery-ui': 'vendor/jquery/jquery-ui-1.10.4.custom.min',

        'angular': 'vendor/angular-1.5.8/angular.min',
        'angularAMD': 'vendor/angularAMD/angularAMD.min',
        'angular-ui-router': "vendor/angular-1.5.8/angular-ui-router",
        'angular-cookies': 'vendor/angular-1.5.8/angular-cookies.min',

        'route': 'route',
        'const': 'const',
        'helper': '../helper',

        'select2': 'vendor/select2/select2.min',
        'ui-bootstrap': 'vendor/ui-bootstrap/ui-bootstrap',
        'bootstrap': 'vendor/bootstrap/js/bootstrap.min',
        'angular-tree': 'vendor/angular-tree/dist/angular-ui-tree.min',
        'fancytree': 'vendor/fancytree/dist/jquery.fancytree-all.min',
        'datepicker_lib': 'vendor/datepicker/js/bootstrap-datepicker',
        'daterange_lib': 'vendor/datepicker/js/daterangepicker',
        'moment': 'vendor/datepicker/js/moment',
        'moment_timezone': 'vendor/datepicker/js/moment-timezone',
        'ckeditor': 'vendor/ng-ckeditor/libs/ckeditor/ckeditor',
        'ngCkeditor': 'vendor/ng-ckeditor/ng-ckeditor',
        'hotkey': 'vendor/angular-hotkeys/build/hotkeys',
        'fullcalendar': 'vendor/fullcalendar/js/fullcalendar.min',
        'calendar': 'vendor/fullcalendar/js/calendar.min',
        'trumbowyg': 'vendor/trumbowyg/dist/trumbowyg.min',
        'trumbowyg_color': 'vendor/trumbowyg/dist/plugins/colors/trumbowyg.colors.min',
        'barcode': 'vendor/JsBarcode.all',
        'qrcode': 'vendor/qrcode.min',

        'moment_min': 'vendor/fullcalendar/lib/moment.min',

        // fileuploader
        'fileupload': 'vendor/fileuploader/js/jquery.fileupload',
        'iframe-transport': 'vendor/fileuploader/js/jquery.iframe-transport',
        'canvas-to-blob': 'vendor/fileuploader/js/canvas-to-blob.min',
        'blueimp-gallery': 'vendor/fileuploader/js/jquery.blueimp-gallery.min',
        'fileupload-process': 'vendor/fileuploader/js/jquery.fileupload-process',
        'fileupload-image': 'vendor/fileuploader/js/jquery.fileupload-image',
        'fileupload-audio': 'vendor/fileuploader/js/jquery.fileupload-audio',
        'fileupload-video': 'vendor/fileuploader/js/jquery.fileupload-video',
        'fileupload-validate': 'vendor/fileuploader/js/jquery.fileupload-validate',
        'fileupload-ui': 'vendor/fileuploader/js/jquery.fileupload-ui',
        'load-image': 'vendor/fileuploader/js/load-image',
        'load-image-meta': 'vendor/fileuploader/js/load-image-meta',
        'load-image-exif': 'vendor/fileuploader/js/load-image-exif',
        'load-image-ios': 'vendor/fileuploader/js/load-image-ios',
        'tmpl': 'vendor/fileuploader/js/tmpl.min',

        // Directives
        'plugin': 'js/directives/pluginDirectives',
        'ui-select2': 'js/directives/ui-select2',
        'attribute': 'js/directives/attribute',
        'datepicker': 'js/directives/datepicker',
        'ng-upload': 'js/directives/ngUpload',
        'report': 'js/directives/report',
        'stock': 'js/directives/stock',
        'textEditor': 'js/directives/textEditor',
        'myPrefix': 'js/directives/myPrefix',
        'myTnc': 'js/directives/myTnc',
        'myCalendar': 'js/directives/myCalendar',
        'searchMenu': 'js/directives/searchMenu',
        'myForm': 'js/directives/myForm',
        'whatsappNo': 'js/directives/whatsappNo',
        // Services
        'auth': 'js/services/auth',
        'httpInterceptor': 'js/services/httpInterceptor',
        'table': 'js/services/table',
        'tableEdit': 'js/services/tableEdit',
        'stickyMessage': 'js/services/stickyMessage',
        'import': 'js/services/import',
        'chart': 'js/services/chart',
        'icons': 'js/services/icons',
        'date': 'js/services/date',
        'help': 'js/services/help',
        'unitService': 'js/services/unitService',
        'templateService': 'js/services/templateService',
        'settingService': 'js/services/settingService',
        'popupService': 'js/services/popupService',

        // module service for pop up
        'expenseService': 'modules/expense/expense/expenseService',
        'expenseTypeService': 'modules/expense/expenseType/expenseTypeService',
        'leadIndustryService': 'modules/lead/leadIndustry/leadIndustryService',
        'leadSourceService': 'modules/lead/leadSource/leadSourceService',
        'leadStatusService': 'modules/lead/leadStatus/leadStatusService',
        'transportService': 'modules/transport/transportService',
        'productCategoryService': 'modules/catalog/productCategory/productCategoryService',
        'productUnitService': 'modules/catalog/productUnit/productUnitService',
        'dealLostService': 'modules/deal/dealLost/dealLostService',
        'areaService': 'modules/area/areaService',
        'paymentTypeService': 'modules/paymentCollection/paymentType/paymentTypeService',
        'productRate': 'modules/catalog/priceGroup/servicesProductRate',
        'activityService': 'modules/activity/activity/activityService',
        'smsService': 'modules/sms/sms/smsService',
        'mailService': 'modules/mail/mail/mailService',
        'visitService': 'modules/visit/visitService',
        'productService': 'modules/order/productService',
        'warehouseService': 'modules/warehouse/warehouseService',
        'leaveTypeService': 'modules/leave/leaveType/leaveTypeService',
        'processService': 'modules/process/processService',
        'termsService': 'modules/terms/termsService',
        'prefixService': 'modules/prefix/prefixService',
        'workProfileService': 'modules/workProfile/workProfileService',
        'targetTypeService': 'modules/targetType/targetTypeService',
        'locationService': 'modules/location/locationService',
        'complaintTypeService': 'modules/complaint/complaintType/complaintTypeService',
        'complaintFeedbackTypeService': 'modules/complaint/complaintFeedbackType/complaintFeedbackTypeService',
        'brandService': 'modules/brand/brandService',
        'accountCategoryService': 'modules/accountCategory/accountCategoryService',
        'userWarehouseService': 'modules/plugin/684301/userWarehouse/userWarehouseService',
    },

    // Add angular modules that does not support AMD out of the box, put it in a shim
    shim: {
        'angular': ['jquery'],
        'jquery-ui': ['jquery'],
        'fancytree': ['jquery'],
        'angularAMD': ['angular', 'jquery'],
        'angular-ui-router': ['angular'],
        'angular-cookies': ['angular'],
        'select2': ['angular', 'jquery'],
        'ui-bootstrap': ['angular', 'jquery'],
        'bootstrap': ['angular', 'jquery'],
        'angular-tree': ['angular', 'jquery'],
        'datepicker_lib': ['angular', 'jquery'],
        'hotkey': ['angular'],
        'fullcalendar': ['angular', 'jquery', 'moment_min'],
        'calendar': ['angular', 'jquery', 'moment_min']
    },

    // kick start application
    deps: ['app']
});